default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: poli_prueba_development

test:
  <<: *default
  database: poli_prueba_test

production:
  <<: *default
  database: poli_prueba_production
  username: <%= ENV['POLI_PRUEBA_DATABASE_USER'] %>
  password: <%= ENV['POLI_PRUEBA_DATABASE_PASSWWORD'] %>
